export { default as Home } from './Home/Home'
export { default as NotFound } from './NotFound'

// 30 days
export { default as Day01 } from './D01Drums/DrumKit'
export { default as Day02 } from './D01Drums/DrumKit'
export { default as Day03 } from './D01Drums/DrumKit'
export { default as Day04 } from './D01Drums/DrumKit'
export { default as Day05 } from './D01Drums/DrumKit'
export { default as Day06 } from './D01Drums/DrumKit'
export { default as Day07 } from './D01Drums/DrumKit'
export { default as Day08 } from './D01Drums/DrumKit'
export { default as Day09 } from './D01Drums/DrumKit'
export { default as Day10 } from './D01Drums/DrumKit'

export { default as Day11 } from './D01Drums/DrumKit'
export { default as Day12 } from './D01Drums/DrumKit'
export { default as Day13 } from './D01Drums/DrumKit'
export { default as Day14 } from './D01Drums/DrumKit'
export { default as Day15 } from './D01Drums/DrumKit'
export { default as Day16 } from './D01Drums/DrumKit'
export { default as Day17 } from './D01Drums/DrumKit'
export { default as Day18 } from './D01Drums/DrumKit'
export { default as Day19 } from './D01Drums/DrumKit'
export { default as Day20 } from './D01Drums/DrumKit'

export { default as Day21 } from './D01Drums/DrumKit'
export { default as Day22 } from './D01Drums/DrumKit'
export { default as Day23 } from './D01Drums/DrumKit'
export { default as Day24 } from './D01Drums/DrumKit'
export { default as Day25 } from './D01Drums/DrumKit'
export { default as Day26 } from './D01Drums/DrumKit'
export { default as Day27 } from './D01Drums/DrumKit'
export { default as Day28 } from './D01Drums/DrumKit'
export { default as Day29 } from './D01Drums/DrumKit'